{% set version = "4.9.4" %}
{% set name = "tensorflow-datasets" %}

# This is the recipe for tensorflow-datasets
package:
   name: {{ name }}
   version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/fe/18/4865973f5469cfe33bbe1cfc2f1918335eb44f4cc3d316c1bce22c1af2bc/tensorflow_datasets-{{ version }}-py3-none-any.whl
  sha256: cbf93bf87531605ea654d702763b9162546775c7aa3247975d502fd921c39e4d

build:
  number: 3
  noarch: python
  string: pyh{{ PKG_HASH }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}
  script: "python -m pip install tensorflow_datasets-{{ version }}*.whl --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
     - python 
  build:
     - git >=2.2 
  run:
   # conda build requirements
     - python 
     - absl-py {{ absl_py }}
     - attrs {{ attrs }}
     - array-record {{ array_record }}
     - etils
     - dill 
     - numpy {{ numpy }}
     - promise
     - protobuf {{ protobuf }}
     - psutil {{ psutil }}
     - requests {{ requests }}
     - six {{ six }}
     - tensorflow-metadata
     - toml
     - tqdm {{ tqdm }}
     - wrapt {{ wrapt }}
     - dm-tree {{ dm_tree }}
     - typing_extensions {{ typing_extensions }}        #[py<38]
     - importlib_resources {{ importlib_resources }}    #[py<39]
     - tensorflow-base {{ tensorflow }}
  test:
    imports:
      - tensorflow
      - tensorflow_datasets

about:
  home: https://github.com/tensorflow/datasets
  license: Apache License 2.0
  license_family: APACHE
  license_file: ../LICENSE
  summary: "A collection of datasets ready to use with TensorFlow"
  description: |
      tensorflow-datasets is a library of public datasets ready to use with
      TensorFlow. Each dataset definition contains the logic necessary to 
      download and prepare the dataset, as well as to read it into a model using the
      `tf.data.Dataset` API.
      Usage outside of TensorFlow is also supported.
  dev_url: https://github.com/tensorflow/datasets.git
  doc_url: https://github.com/tensorflow/datasets.git 

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
