{% set version = "4.8.2" %}
{% set name = "tensorflow-datasets" %}

# This is the recipe for tensorflow-datasets
package:
   name: {{ name }}
   version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/c2/2a/c1aa78b0211b1e3f6439d4edabd44bfb6e1c45544a7a241e3ba5cfe3c316/tensorflow_datasets-{{ version }}-py3-none-any.whl
  sha256: b11503c0410cb6752f8619c97e5a45c5fee22ff4e164aa1bfefadb401721e2e1 

build:
  number: 1
  noarch: python
  string: pyh{{ PKG_HASH }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}
  script: "python -m pip install tensorflow_datasets-{{ version }}*.whl --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
     - python 
  build:
     - git >=2.2 
  run:
   # conda build requirements
     - python 
     - absl-py {{ absl_py }}
     - attrs {{ attrs }} 
     - etils
     - dill 
     - numpy {{ numpy }}
     - promise
     - protobuf {{ protobuf }}
     - requests {{ requests }}
     - six {{ six }}
     - tensorflow-metadata
     - termcolor {{ termcolor }}
     - toml
     - tqdm {{ tqdm }}
     - wrapt {{ wrapt }}
     - dm-tree {{ dm_tree }}
     - typing_extensions {{ typing_extensions }}        #[py<38]
     - importlib_resources {{ importlib_resources }}    #[py<39]
     - tensorflow-base {{ tensorflow }}

about:
  home: https://github.com/tensorflow/datasets
  license: Apache License 2.0
  license_family: APACHE
  license_file: ../LICENSE
  summary: "A collection of datasets ready to use with TensorFlow"
  description: |
      tensorflow-datasets is a library of public datasets ready to use with
      TensorFlow. Each dataset definition contains the logic necessary to 
      download and prepare the dataset, as well as to read it into a model using the
      `tf.data.Dataset` API.
      Usage outside of TensorFlow is also supported.
  dev_url: https://github.com/tensorflow/datasets.git
  doc_url: https://github.com/tensorflow/datasets.git 

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
